# Generated by Django 6.0.7 on 2026-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category name (EN)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredients (EN)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dish name (EN)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва категорії (UA)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(verbose_name='Опис (UA)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Інгредієнти (UA)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва страви (UA)'),
        ),
    ]
